apiVersion: v1
kind: Service
metadata:
  name: history-service
spec:
  selector:
    app: history-service  # This must match the label in the Deployment
  ports:
    - protocol: TCP
      port: 80       # The port exposed by the service
      targetPort: 5006  # The port on which the application is running
  type: ClusterIP  # This will expose the service internally. Use NodePort if you want external access.
