apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1  # Number of instances (adjust as needed)
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: frontend:latest  # Replace with your exact image name if different
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000  # Port exposed by the Docker container
