apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
        - name: history-service
          image: history-service:latest
          ports:
            - containerPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: history-service
spec:
  selector:
    app: history-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5006
  type: ClusterIP
