apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-info-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: public-info-service
  template:
    metadata:
      labels:
        app: public-info-service
    spec:
      containers:
        - name: public-info-service
          image: public-info-service:latest
          ports:
            - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: public-info-service
spec:
  selector:
    app: public-info-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
  type: ClusterIP
