apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-reporting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: utility-reporting-service
  template:
    metadata:
      labels:
        app: utility-reporting-service
    spec:
      containers:
        - name: utility-reporting-service
          image: utility-reporting-service:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: utility-reporting-service
spec:
  selector:
    app: utility-reporting-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
