apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 80        # Port exposed within the cluster
      targetPort: 5005 # Port on the container
  type: ClusterIP  # Internal access; use NodePort if you need external access
