apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service  # This must match the label in the Deployment
  ports:
    - protocol: TCP
      port: 80         # The port on which the service will be accessible
      targetPort: 5000 # The port the container is listening on
  type: ClusterIP  # Internal access within the cluster; change to NodePort if external access is needed
